version: '3'
services:
  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db-postgres
    networks:
      - fullstack

  db-postgres:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=${POSTGRES_PORT}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack


volumes:
  api:
  database_postgres:

networks:
  fullstack:
    driver: bridge